sudo: require

install:
  - sudo pip install proselint

script: 
  # Satisfy proselint, as it reads code as if it is prose
  # Remove all quotes and apostrophs
  - sed -i 's/`//g' README.md
  - sed -i 's/"//g' README.md
  - cat README.md
  # Proseline
  - proselint README.md
